[[override]]
  name = "github.com/tendermint/tendermint"
  version = "0.23.0"

[[override]]
  name = "github.com/yuin/gopher-lua"
  branch = "master"

[[override]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
