[[override]]
  name = "github.com/tendermint/tendermint"
  version = "0.25.0"

[[override]]
  name = "github.com/yuin/gopher-lua"
  branch = "master"

[[override]]
  name = "layeh.com/gopher-json"
  branch = "master"

[[override]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[override]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[override]]
  name = "github.com/dedis/kyber"
  branch = "master"

[[override]]
  name = "github.com/go-resty/resty"
  version = "1.9.1"

[[override]]
  name = "github.com/montanaflynn/stats"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true
